version: '3.8'

services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/kotlinapp_dev
      - SPRING_DATASOURCE_USERNAME=dev_user
      - SPRING_DATASOURCE_PASSWORD=dev_pass
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle

  postgres:
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=kotlinapp_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data

volumes:
  postgres-data-dev:
  gradle-cache: